# Generated by Django 5.2.17 on 2026-09-30 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_inventoryreservation_source_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedAnalysisView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("dataset", models.CharField(max_length=40)),
                ("configuration", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_views",
                        to="inventory.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "dataset", "shared"],
                        name="analytics_s_tenant__5b0ef8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "owner", "name"),
                        name="analytics_unique_saved_view",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedFilterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("dataset", models.CharField(max_length=40)),
                ("conditions", models.JSONField(default=list)),
                ("shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_filter_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_filter_groups",
                        to="inventory.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "owner", "name"),
                        name="analytics_unique_filter_group",
                    )
                ],
            },
        ),
    ]
