# Generated by Django 5.2.17 on 2026-09-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_supplierinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('gl_journal', 'G/L Journal'), ('sales_invoice', 'Sales Invoice'), ('sales_credit_memo', 'Sales Credit Memo'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_credit_memo', 'Purchase Credit Memo'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('fixed_asset', 'Fixed Asset'), ('gst_invoice', 'GST Invoice'), ('e_invoice', 'E-Invoice'), ('e_way_bill', 'E-Way Bill')], max_length=30)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_number_series', to='erp.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'fiscal_year'), name='unique_document_series_per_company_year')],
            },
        ),
    ]
