# Generated by Django 5.2.17 on 2026-09-19 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_brand_channel_costcenter_store_dimensionset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='binlocation',
            name='aisle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_mixed_items',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_mixed_lots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_mixed_serials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_pick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='allow_putaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='capacity_unit',
            field=models.CharField(default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='current_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='current_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='max_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='position',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='rack',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='rank',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='binlocation',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='erp.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='allow_cross_docking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='allow_negative_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='allow_replenishment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='bin_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='erp.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='directed_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='directed_putaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('ecommerce', 'E-commerce'), ('factory', 'Factory'), ('3pl', '3PL'), ('return_center', 'Return Center'), ('quarantine', 'Quarantine'), ('transit', 'Transit')], default='warehouse', max_length=30),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='require_inventory_movement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='require_pick',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='require_putaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='require_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='require_shipment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=100),
        ),
        migrations.AlterField(
            model_name='binlocation',
            name='bin_type',
            field=models.CharField(choices=[('bulk', 'Bulk'), ('pick', 'Pick'), ('putaway', 'Putaway'), ('replenishment', 'Replenishment'), ('damaged', 'Damaged'), ('receiving', 'Receiving'), ('shipping', 'Shipping'), ('quarantine', 'Quarantine'), ('return', 'Return'), ('staging', 'Staging'), ('scrap', 'Scrap')], default='bulk', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentnumberseries',
            name='document_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('gl_journal', 'G/L Journal'), ('sales_invoice', 'Sales Invoice'), ('sales_credit_memo', 'Sales Credit Memo'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_credit_memo', 'Purchase Credit Memo'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('fixed_asset', 'Fixed Asset'), ('gst_invoice', 'GST Invoice'), ('e_invoice', 'E-Invoice'), ('e_way_bill', 'E-Way Bill'), ('transfer_order', 'Transfer Order'), ('warehouse_receipt', 'Warehouse Receipt'), ('putaway', 'Put-away'), ('pick', 'Pick'), ('warehouse_shipment', 'Warehouse Shipment'), ('movement', 'Warehouse Movement'), ('replenishment', 'Replenishment'), ('inventory_adjustment', 'Inventory Adjustment'), ('item_journal', 'Item Journal'), ('stock_take', 'Stock Take'), ('cycle_count', 'Cycle Count'), ('qc_inspection', 'QC Inspection'), ('customer_return', 'Customer Return'), ('vendor_return', 'Vendor Return'), ('scrap', 'Scrap'), ('reclassification', 'Reclassification'), ('cross_dock', 'Cross Dock')], max_length=30),
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(choices=[('receiving', 'Receiving'), ('putaway', 'Put-away'), ('bulk', 'Bulk'), ('picking', 'Picking'), ('fast_pick', 'Fast Pick'), ('reserve', 'Reserve'), ('replenishment', 'Replenishment'), ('qc', 'QC'), ('quarantine', 'Quarantine'), ('damage', 'Damage'), ('return', 'Return'), ('staging', 'Staging'), ('shipping', 'Shipping'), ('cross_dock', 'Cross Dock'), ('packing', 'Packing'), ('scrap', 'Scrap')], default='bulk', max_length=30)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('security_level', models.PositiveSmallIntegerField(default=0)),
                ('allow_pick', models.BooleanField(default=True)),
                ('allow_putaway', models.BooleanField(default=True)),
                ('allow_movement', models.BooleanField(default=True)),
                ('allow_replenishment', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked')], default='draft', max_length=20)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='erp.warehouse')),
            ],
            options={
                'ordering': ['priority', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='binlocation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bins', to='erp.warehousezone'),
        ),
        migrations.CreateModel(
            name='WarehouseUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('receive', 'Receive'), ('putaway', 'Put-away'), ('pick', 'Pick'), ('move', 'Move'), ('count', 'Count'), ('qc', 'QC'), ('ship', 'Ship')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='erp.warehouse')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='erp.warehousezone')),
            ],
            options={
                'unique_together': {('user', 'warehouse', 'zone', 'operation')},
            },
        ),
    ]
