# Generated by Django 5.2.17 on 2026-09-19 20:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_gstcomponent_gstgroup_gstrate_gststate_supplytype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceJournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('operation_type', models.CharField(default='general_journal', max_length=40)),
                ('voucher_type', models.CharField(default='journal_voucher', max_length=40)),
                ('source_code', models.CharField(blank=True, max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('approval_required', models.BooleanField(default=True)),
                ('auto_post_allowed', models.BooleanField(default=False)),
                ('recurring_allowed', models.BooleanField(default=False)),
                ('reversal_allowed', models.BooleanField(default=True)),
                ('allow_dimensions', models.BooleanField(default=True)),
                ('allow_gst', models.BooleanField(default=True)),
                ('allow_tds', models.BooleanField(default=True)),
                ('allow_foreign_currency', models.BooleanField(default=True)),
                ('allow_attachment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentnumberseries',
            name='document_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('gl_journal', 'G/L Journal'), ('sales_invoice', 'Sales Invoice'), ('sales_credit_memo', 'Sales Credit Memo'), ('purchase_invoice', 'Purchase Invoice'), ('purchase_credit_memo', 'Purchase Credit Memo'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('fixed_asset', 'Fixed Asset'), ('gst_invoice', 'GST Invoice'), ('e_invoice', 'E-Invoice'), ('e_way_bill', 'E-Way Bill'), ('transfer_order', 'Transfer Order'), ('warehouse_receipt', 'Warehouse Receipt'), ('putaway', 'Put-away'), ('pick', 'Pick'), ('warehouse_shipment', 'Warehouse Shipment'), ('movement', 'Warehouse Movement'), ('replenishment', 'Replenishment'), ('inventory_adjustment', 'Inventory Adjustment'), ('item_journal', 'Item Journal'), ('stock_take', 'Stock Take'), ('cycle_count', 'Cycle Count'), ('qc_inspection', 'QC Inspection'), ('customer_return', 'Customer Return'), ('vendor_return', 'Vendor Return'), ('scrap', 'Scrap'), ('reclassification', 'Reclassification'), ('cross_dock', 'Cross Dock'), ('journal_voucher', 'Journal Voucher'), ('cash_receipt', 'Cash Receipt Voucher'), ('cash_payment', 'Cash Payment Voucher'), ('bank_receipt', 'Bank Receipt Voucher'), ('bank_payment', 'Bank Payment Voucher'), ('contra_voucher', 'Contra Voucher'), ('payment_journal', 'Payment Journal'), ('receipt_journal', 'Receipt Journal'), ('adjustment_journal', 'Adjustment Journal'), ('accrual_journal', 'Accrual Journal'), ('provision_journal', 'Provision Journal'), ('reversal_journal', 'Reversal Journal')], max_length=30),
        ),
        migrations.CreateModel(
            name='FinanceJournalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('source_code', models.CharField(blank=True, max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_journal_batches', to='erp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_journal_batches', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='erp.financejournaltemplate')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FinancePostedVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('voucher_no', models.CharField(max_length=60)),
                ('posting_no', models.CharField(max_length=60, unique=True)),
                ('posting_date', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('narration', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_voucher_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancePostedVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('account_code', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('posted_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.financepostedvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=60, unique=True)),
                ('posting_no', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('document_no', models.CharField(blank=True, max_length=100)),
                ('external_document_no', models.CharField(blank=True, max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today)),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('narration', models.TextField(blank=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('approval_status', models.CharField(default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_vouchers', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='erp.financejournalbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_vouchers', to='erp.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_vouchers', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_finance_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='financepostedvoucher',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posted_snapshot', to='erp.financevoucher'),
        ),
        migrations.CreateModel(
            name='FinanceVoucherApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_approvals', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='erp.financevoucher')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceVoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='journal', max_length=40)),
                ('approval_required', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=False)),
                ('allow_customer', models.BooleanField(default=True)),
                ('allow_vendor', models.BooleanField(default=True)),
                ('allow_bank', models.BooleanField(default=True)),
                ('allow_cash', models.BooleanField(default=True)),
                ('allow_tax', models.BooleanField(default=True)),
                ('allow_dimensions', models.BooleanField(default=True)),
                ('allow_reversal', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_voucher_types', to='erp.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_types', to='erp.financejournaltemplate')),
            ],
        ),
        migrations.AddField(
            model_name='financevoucher',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='erp.financevouchertype'),
        ),
        migrations.CreateModel(
            name='FinanceVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=250)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_voucher_lines', to='erp.glaccount')),
                ('dimension_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_voucher_lines', to='erp.dimensionset')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='erp.financevoucher')),
            ],
            options={
                'ordering': ['line_no'],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'line_no'), name='unique_finance_voucher_line')],
            },
        ),
        migrations.AddConstraint(
            model_name='financevouchertype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_finance_voucher_type'),
        ),
    ]
