# Generated by Django 5.2.17 on 2026-09-19 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_financejournaltemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPostingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('advance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_advance_groups', to='erp.glaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_posting_groups', to='erp.company')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_posting_groups', to='erp.glaccount')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('method_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('card', 'Card'), ('gateway', 'Payment Gateway'), ('other', 'Other')], default='bank', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('due_days', models.PositiveIntegerField(default=0)),
                ('discount_days', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_hold', models.BooleanField(default=False)),
                ('allow_sales', models.BooleanField(default=True)),
                ('allow_credit', models.BooleanField(default=True)),
                ('allow_refund', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to='erp.customer')),
                ('posting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='erp.customerpostinggroup')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='erp.paymentmethod')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profiles', to='erp.paymentterm')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPostingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('advance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_advance_groups', to='erp.glaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_posting_groups', to='erp.company')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_posting_groups', to='erp.glaccount')),
            ],
        ),
        migrations.CreateModel(
            name='VendorFinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('payment_hold', models.BooleanField(default=False)),
                ('purchase_hold', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profiles', to='erp.paymentmethod')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profiles', to='erp.paymentterm')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to='erp.supplier')),
                ('posting_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profiles', to='erp.vendorpostinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.PositiveBigIntegerField()),
                ('relationship_type', models.CharField(default='derived_from', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='erp_documen_source__75f552_idx'), models.Index(fields=['target_type', 'target_id'], name='erp_documen_target__1934cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type', 'target_id', 'relationship_type'), name='unique_document_relationship')],
            },
        ),
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_id', models.PositiveBigIntegerField()),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'document_id', 'changed_at'], name='erp_documen_documen_23a32f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_payment_method_scope'),
        ),
        migrations.AddConstraint(
            model_name='paymentterm',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_payment_term_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorpostinggroup',
            unique_together={('company', 'code')},
        ),
    ]
