# Generated by Django 5.2.17 on 2026-09-20 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_customerpostinggroup_paymentmethod_paymentterm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='erp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_divisions', to='erp.company')),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('inventory', 'Inventory'), ('service', 'Service'), ('kit', 'Kit'), ('bundle', 'Bundle'), ('consumable', 'Consumable')], default='inventory', max_length=30)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('variant_mandatory', models.BooleanField(default=False)),
                ('lot_tracking', models.BooleanField(default=False)),
                ('serial_tracking', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_items', to='erp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_items', to='erp.company')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.division')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='erp.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reorder_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('active', models.BooleanField(default=True)),
                ('default_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_item_setups', to='erp.binlocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_setups', to='erp.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_setups', to='erp.location')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_setups', to='erp.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='erp.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_skus', to='erp.location')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='erp.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_groups', to='erp.division')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='special_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.specialgroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='special_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='erp.specialgroup'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='erp.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.subcategory'),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='erp.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_uom', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('is_purchase_uom', models.BooleanField(default=False)),
                ('is_sales_uom', models.BooleanField(default=False)),
                ('is_inventory_uom', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='erp.item')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_conversions', to='erp.unitofmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_items', to='erp.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('barcode_type', models.CharField(choices=[('ean13', 'EAN-13'), ('upc', 'UPC'), ('gtin', 'GTIN'), ('code128', 'Code 128'), ('internal', 'Internal'), ('gs1', 'GS1')], default='internal', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_barcodes', to='erp.sku')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retail_barcodes', to='erp.unitofmeasure')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'code'), name='unique_item_variant'),
        ),
        migrations.AddConstraint(
            model_name='itemlocation',
            constraint=models.UniqueConstraint(fields=('item', 'variant', 'location'), name='unique_item_location_setup'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('item', 'variant', 'location'), name='unique_item_variant_location_sku'),
        ),
        migrations.AlterUniqueTogether(
            name='specialgroup',
            unique_together={('division', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('special_group', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'code')},
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_uom_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='itemunitofmeasure',
            unique_together={('item', 'uom')},
        ),
    ]
