# Generated by Django 5.2.17 on 2026-09-21 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_category_division_item_itemvariant_itemlocation_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('logged_out', 'Logged out'), ('expired', 'Expired'), ('locked', 'Locked')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cashier_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cashier_role_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_staff_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='store_code_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terminal_code_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='pos_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.possession'),
        ),
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(max_length=50, unique=True)),
                ('opening_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='open', max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_shifts', to='erp.store')),
            ],
        ),
        migrations.AddField(
            model_name='possession',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='erp.posshift'),
        ),
        migrations.CreateModel(
            name='POSStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('sales_staff', 'Sales Staff')], default='cashier', max_length=20)),
                ('pin_hash', models.CharField(max_length=128)),
                ('pos_access', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_staff', to='erp.store')),
            ],
        ),
        migrations.AddField(
            model_name='posshift',
            name='closing_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to='erp.posstaff'),
        ),
        migrations.AddField(
            model_name='posshift',
            name='opening_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_shifts', to='erp.posstaff'),
        ),
        migrations.AddField(
            model_name='possession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='erp.posstaff'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cashier_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_invoices', to='erp.posstaff'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_staff_invoices', to='erp.posstaff'),
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('printer', models.CharField(blank=True, max_length=100)),
                ('cash_drawer', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_transaction', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='erp.store')),
            ],
        ),
        migrations.CreateModel(
            name='POSStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('sales_staff', 'Sales Staff')], max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('primary_terminal', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='erp.posstaff')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='erp.posterminal')),
            ],
        ),
        migrations.AddField(
            model_name='posshift',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='erp.posterminal'),
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='erp.posterminal'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp.posterminal'),
        ),
        migrations.AddConstraint(
            model_name='posterminal',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_pos_terminal_store_code'),
        ),
        migrations.AddConstraint(
            model_name='posstaffassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'terminal', 'role'), name='unique_pos_staff_terminal_role'),
        ),
    ]
