# Generated by Django 5.2.17 on 2026-09-21 18:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_possession_salesinvoice_cashier_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='certification_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='diamond_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='gemstone_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='hallmark_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='metal_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='metal_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='net_metal_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='stone_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='wastage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='JewelleryItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('design_id', models.CharField(blank=True, max_length=100)),
                ('huid', models.CharField(blank=True, max_length=100)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stone_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('other_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('metal_type', models.CharField(blank=True, max_length=30)),
                ('purity', models.CharField(blank=True, max_length=30)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('held', 'Held'), ('sold', 'Sold'), ('returned', 'Returned'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('current_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jewellery_units', to='erp.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jewellery_units', to='erp.product')),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='jewellery_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_invoice_items', to='erp.jewelleryitemunit'),
        ),
        migrations.CreateModel(
            name='JewelleryMetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(max_length=30)),
                ('purity', models.CharField(max_length=30)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate_type', models.CharField(default='selling', max_length=30)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jewellery_metal_rates', to='erp.store')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('making_method', models.CharField(choices=[('percent', 'Percentage'), ('per_gram', 'Per gram'), ('fixed', 'Fixed amount')], default='percent', max_length=20)),
                ('making_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wastage_method', models.CharField(choices=[('weight', 'Weight x rate'), ('percent', 'Metal value percentage')], default='weight', max_length=20)),
                ('wastage_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('hallmark_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('certification_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate_code', models.CharField(default='GST-3', max_length=40)),
                ('requires_huid', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jewellery_pricing_rule', to='erp.product')),
            ],
        ),
        migrations.CreateModel(
            name='JewelleryStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_type', models.CharField(max_length=50)),
                ('stone_name', models.CharField(blank=True, max_length=100)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('carat', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('rate_per_carat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fixed_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='erp.jewelleryitemunit')),
            ],
        ),
    ]
