# Generated by Django 5.2.17 on 2026-09-22 17:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_salesinvoiceitem_certification_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('maximum_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approval_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('calculation_method', models.CharField(default='standard', max_length=30)),
                ('price_includes_tax', models.BooleanField(default=False)),
                ('allow_line_discount', models.BooleanField(default=True)),
                ('allow_invoice_discount', models.BooleanField(default=True)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_posting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='erp.customerpostinggroup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_customer_type',
            field=models.CharField(default='unregistered', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_registration_type',
            field=models.CharField(default='GSTIN', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_state_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_verification_status',
            field=models.CharField(default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(default='en-IN', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('address_3', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=5)),
                ('country', models.CharField(default='India', max_length=100)),
                ('country_code', models.CharField(default='IN', max_length=3)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='erp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_consent', models.BooleanField(default=False)),
                ('email_consent', models.BooleanField(default=False)),
                ('whatsapp_consent', models.BooleanField(default=False)),
                ('phone_consent', models.BooleanField(default=False)),
                ('promotional_consent', models.BooleanField(default=False)),
                ('transactional_consent', models.BooleanField(default=True)),
                ('consent_source', models.CharField(blank=True, max_length=80)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to='erp.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_discount_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='erp.customerdiscountgroup'),
        ),
        migrations.CreateModel(
            name='CustomerDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(default='total', max_length=30)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('minimum_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='erp.customerdiscountgroup')),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount_rules', to='erp.itemcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_discount_rules', to='erp.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('AADHAAR', 'Aadhaar'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', 'Driving licence'), ('OTHER', 'Other')], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('name_on_document', models.CharField(blank=True, max_length=200)),
                ('verification_status', models.CharField(default='unverified', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='erp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerJewelleryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_metal', models.CharField(blank=True, max_length=30)),
                ('preferred_purity', models.CharField(blank=True, max_length=30)),
                ('preferred_category', models.CharField(blank=True, max_length=100)),
                ('preferred_style', models.CharField(blank=True, max_length=100)),
                ('preferred_stone', models.CharField(blank=True, max_length=100)),
                ('budget_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_maximum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('preferred_occasion', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jewellery_preferences', to='erp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('pan_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('risk_category', models.CharField(default='standard', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='erp.customer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_customer_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMarketingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(blank=True, max_length=80)),
                ('tier', models.CharField(blank=True, max_length=80)),
                ('loyalty_number', models.CharField(blank=True, max_length=80)),
                ('loyalty_points', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('campaign_name', models.CharField(blank=True, max_length=120)),
                ('first_purchase_date', models.DateField(blank=True, null=True)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_profile', to='erp.customer')),
                ('preferred_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='erp.store')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_price_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='erp.customerpricegroup'),
        ),
        migrations.CreateModel(
            name='CustomerNumberSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='CUS', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_number_series', to='erp.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_number_series', to='erp.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'store'), name='unique_customer_number_series_scope')],
            },
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_code', models.CharField(max_length=30)),
                ('address_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('address_1', models.CharField(blank=True, max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=5)),
                ('country', models.CharField(default='India', max_length=100)),
                ('country_code', models.CharField(default='IN', max_length=3)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='erp.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'address_code'), name='unique_customer_shipping_address_code')],
            },
        ),
    ]
