# Generated by Django 5.2.17 on 2026-09-22 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_customerdiscountgroup_customerpricegroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePrintLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('print_type', models.CharField(choices=[('A4_INVOICE', 'A4 Invoice'), ('A5_INVOICE', 'A5 Invoice'), ('THERMAL_40COL_RECEIPT', '40 Column Receipt')], max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='print_layout_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='print_layout_version_snapshot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='print_type_snapshot',
            field=models.CharField(default='A4_INVOICE', max_length=40),
        ),
        migrations.CreateModel(
            name='InvoicePrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_type', models.CharField(max_length=40)),
                ('layout_code', models.CharField(blank=True, max_length=40)),
                ('layout_version', models.PositiveIntegerField(default=1)),
                ('printer_name', models.CharField(blank=True, max_length=120)),
                ('printed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(default='original', max_length=200)),
                ('original', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_logs', to='erp.salesinvoice')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_print_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSTerminalPrintSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_type', models.CharField(blank=True, choices=[('A4_INVOICE', 'A4 Invoice'), ('A5_INVOICE', 'A5 Invoice'), ('THERMAL_40COL_RECEIPT', '40 Column Receipt')], max_length=40)),
                ('printer_name', models.CharField(blank=True, max_length=120)),
                ('auto_print', models.BooleanField(default=False)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_setups', to='erp.invoiceprintlayout')),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_setup', to='erp.posterminal')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInvoicePrintSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_print_type', models.CharField(choices=[('A4_INVOICE', 'A4 Invoice'), ('A5_INVOICE', 'A5 Invoice'), ('THERMAL_40COL_RECEIPT', '40 Column Receipt')], default='A4_INVOICE', max_length=40)),
                ('printer_name', models.CharField(blank=True, max_length=120)),
                ('auto_print', models.BooleanField(default=False)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('print_jewellery_details', models.BooleanField(default=True)),
                ('print_weight', models.BooleanField(default=True)),
                ('print_huid', models.BooleanField(default=True)),
                ('print_payment_details', models.BooleanField(default=True)),
                ('print_tax_summary', models.BooleanField(default=True)),
                ('print_terms', models.BooleanField(default=True)),
                ('print_customer_address', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_setups', to='erp.invoiceprintlayout')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_print_setup', to='erp.store')),
            ],
        ),
    ]
