# Generated by Django 5.1.1 on 2026-09-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_remove_purchaseorder_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
