# Generated by Django 5.1.1 on 2026-09-24 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_purchaseorder_order_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jewellerymetalrate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metal_rates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jewellerymetalrate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='jewellerymetalrate',
            name='source_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
