# Generated by Django 5.1.1 on 2026-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0026_alter_documentnumberseries_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentnumberseries",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("gl_journal", "G/L Journal"),
                    ("quotation", "Quotation"),
                    ("sales_order", "Sales Order"),
                    ("payment_receipt", "Payment Receipt"),
                    ("sales_invoice", "Sales Invoice"),
                    ("sales_credit_memo", "Sales Credit Memo"),
                    ("purchase_order", "Purchase Order"),
                    ("goods_receipt", "Goods Receipt"),
                    ("vendor_payment", "Vendor Payment"),
                    ("purchase_invoice", "Purchase Invoice"),
                    ("purchase_credit_memo", "Purchase Credit Memo"),
                    ("payment", "Payment"),
                    ("receipt", "Receipt"),
                    ("fixed_asset", "Fixed Asset"),
                    ("gst_invoice", "GST Invoice"),
                    ("e_invoice", "E-Invoice"),
                    ("e_way_bill", "E-Way Bill"),
                    ("transfer_order", "Transfer Order"),
                    ("warehouse_receipt", "Warehouse Receipt"),
                    ("putaway", "Put-away"),
                    ("pick", "Pick"),
                    ("warehouse_shipment", "Warehouse Shipment"),
                    ("movement", "Warehouse Movement"),
                    ("replenishment", "Replenishment"),
                    ("inventory_adjustment", "Inventory Adjustment"),
                    ("item_journal", "Item Journal"),
                    ("stock_take", "Stock Take"),
                    ("cycle_count", "Cycle Count"),
                    ("qc_inspection", "QC Inspection"),
                    ("customer_return", "Customer Return"),
                    ("vendor_return", "Vendor Return"),
                    ("scrap", "Scrap"),
                    ("reclassification", "Reclassification"),
                    ("cross_dock", "Cross Dock"),
                    ("journal_voucher", "Journal Voucher"),
                    ("sales_journal", "Sales Journal"),
                    ("purchase_journal", "Purchase Journal"),
                    ("cash_receipt", "Cash Receipt Voucher"),
                    ("cash_payment", "Cash Payment Voucher"),
                    ("bank_receipt", "Bank Receipt Voucher"),
                    ("bank_payment", "Bank Payment Voucher"),
                    ("contra_voucher", "Contra Voucher"),
                    ("payment_journal", "Payment Journal"),
                    ("receipt_journal", "Receipt Journal"),
                    ("adjustment_journal", "Adjustment Journal"),
                    ("accrual_journal", "Accrual Journal"),
                    ("provision_journal", "Provision Journal"),
                    ("reversal_journal", "Reversal Journal"),
                    ("production_journal", "Production Journal"),
                    ("scheme_journal", "Jewellery Savings Journal"),
                ],
                max_length=30,
            ),
        ),
    ]
