# Generated by Django 5.2.17 on 2026-09-30 02:58

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def prepare_existing_rows(apps, schema_editor):
    """Mirror legacy is_active flags into the new status fields, and close all but the latest open POS session per
    terminal so the one-open-session constraint can be applied."""
    Store = apps.get_model('erp', 'Store')
    POSTerminal = apps.get_model('erp', 'POSTerminal')
    POSSession = apps.get_model('erp', 'POSSession')
    Store.objects.filter(is_active=False).update(status='inactive')
    POSTerminal.objects.filter(is_active=False, status='active').update(status='inactive')
    seen = set()
    for session in POSSession.objects.filter(status='active').order_by('terminal_id', '-login_time', '-id'):
        if session.terminal_id in seen:
            session.status = 'force_closed'
            session.logout_time = session.last_activity
            session.save(update_fields=['status', 'logout_time'])
        seen.add(session.terminal_id)


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0028_alter_documentnumberseries_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POSPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_code_snapshot", models.CharField(max_length=30)),
                ("tender_name_snapshot", models.CharField(max_length=100)),
                ("tender_type_snapshot", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "change_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("is_refund", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="POSRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "base_role",
                    models.CharField(
                        choices=[
                            ("cashier", "Cashier"),
                            ("manager", "Manager"),
                            ("sales_staff", "Sales Staff"),
                        ],
                        default="cashier",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pos_access",
                    models.BooleanField(
                        default=True,
                        help_text="Staff with this role may log in to POS terminals.",
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="RetailImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("locations", "Locations"),
                            ("stores", "Stores"),
                            ("staff", "Staff"),
                            ("terminals", "POS terminals"),
                            ("tenders", "Tenders"),
                            ("store-tenders", "Store tenders"),
                            ("staff-terminals", "Staff POS assignments"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200)),
                ("rows", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("validated", "Validated"),
                            ("failed", "Has errors"),
                            ("imported", "Imported"),
                        ],
                        default="validated",
                        max_length=20,
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StoreTender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_name_snapshot", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("sequence", models.PositiveSmallIntegerField(default=10)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("requires_reference", models.BooleanField(default=False)),
                ("allow_refund", models.BooleanField(default=True)),
                ("allow_change", models.BooleanField(default=False)),
                ("allow_split_payment", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("sequence", "tender__name"),
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "tender_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("digital", "Digital / UPI"),
                            ("online", "Online gateway"),
                            ("bank", "Bank transfer"),
                            ("cheque", "Cheque"),
                            ("gift_card", "Gift card"),
                            ("store_credit", "Store credit"),
                            ("wallet", "Wallet"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("payment_gateway", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("requires_reference", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("allow_refund", models.BooleanField(default=True)),
                ("allow_change", models.BooleanField(default=False)),
                ("allow_split_payment", models.BooleanField(default=True)),
                ("allow_partial_payment", models.BooleanField(default=True)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="possession",
            name="cash_collected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="possession",
            name="location_code_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="possession",
            name="location_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="possession",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="possession",
            name="refund_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="possession",
            name="role_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="possession",
            name="sales_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="possession",
            name="sales_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="possession",
            name="session_no",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="possession",
            name="staff_code_snapshot",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="possession",
            name="staff_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="possession",
            name="store_code_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="possession",
            name="store_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="possession",
            name="terminal_code_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="possession",
            name="terminal_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posshift",
            name="closing_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="posshift",
            name="location_code_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="default_terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_staff",
                to="erp.posterminal",
            ),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="leaving_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="login_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="password_change_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="active_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="active_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="auto_print",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="barcode_scanner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="customer_display",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="payment_device",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="receipt_printer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="terminal_type",
            field=models.CharField(
                choices=[
                    ("counter", "Billing counter"),
                    ("mobile", "Mobile / tablet"),
                    ("kiosk", "Self-service kiosk"),
                    ("back_office", "Back office"),
                ],
                default="counter",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="cashier_code_snapshot",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="location_code_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="location_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="store_name_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="terminal_name_snapshot",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="closing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="country",
            field=models.CharField(default="India", max_length=60),
        ),
        migrations.AddField(
            model_name="store",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="store",
            name="gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="store",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store",
                to="erp.location",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_stores",
                to="erp.posstaff",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="opening_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="store",
            name="pin_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="store",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blocked", "Blocked"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                choices=[
                    ("flagship", "Flagship"),
                    ("showroom", "Showroom"),
                    ("outlet", "Outlet"),
                    ("franchise", "Franchise"),
                    ("kiosk", "Kiosk"),
                    ("online", "Online"),
                    ("other", "Other"),
                ],
                default="showroom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("approve", "Approve"),
                    ("post", "Post"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("assign", "Assign"),
                    ("unassign", "Unassign"),
                    ("activate", "Activate"),
                    ("deactivate", "Deactivate"),
                    ("lock", "Lock account"),
                    ("unlock", "Unlock account"),
                    ("password_reset", "Password reset"),
                    ("login_failed", "Login failed"),
                ],
                default="create",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="session_key",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="possession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Open"),
                    ("logged_out", "Closed"),
                    ("expired", "Expired"),
                    ("locked", "Locked"),
                    ("force_closed", "Force closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Account locked"),
        ),
        migrations.AlterField(
            model_name="posstaff",
            name="pos_access",
            field=models.BooleanField(default=True, verbose_name="POS login enabled"),
        ),
        migrations.RunPython(prepare_existing_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="possession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("terminal",),
                name="one_open_session_per_terminal",
            ),
        ),
        migrations.AddField(
            model_name="pospayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pos_payments",
                to="erp.salesinvoice",
            ),
        ),
        migrations.AddField(
            model_name="pospayment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="erp.possession",
            ),
        ),
        migrations.AddField(
            model_name="posstaff",
            name="staff_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="erp.posrole",
            ),
        ),
        migrations.AddConstraint(
            model_name="posstaff",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("login_id"),
                name="unique_pos_staff_login_id_ci",
            ),
        ),
        migrations.AddField(
            model_name="retailimportbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storetender",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_tenders",
                to="erp.glaccount",
            ),
        ),
        migrations.AddField(
            model_name="storetender",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_tenders",
                to="erp.store",
            ),
        ),
        migrations.AddField(
            model_name="pospayment",
            name="store_tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="erp.storetender",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenders",
                to="erp.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenders",
                to="erp.glaccount",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment method used when this tender is posted to receivables.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenders",
                to="erp.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="storetender",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store_tenders",
                to="erp.tender",
            ),
        ),
        migrations.AddField(
            model_name="pospayment",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="erp.tender",
            ),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="default_tender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_terminals",
                to="erp.tender",
            ),
        ),
        migrations.AddConstraint(
            model_name="tender",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_amount__isnull", True),
                    ("maximum_amount__isnull", True),
                    ("maximum_amount__gte", models.F("minimum_amount")),
                    _connector="OR",
                ),
                name="tender_min_le_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="storetender",
            constraint=models.UniqueConstraint(
                fields=("store", "tender"), name="unique_store_tender"
            ),
        ),
        migrations.AddConstraint(
            model_name="storetender",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("store",),
                name="one_default_tender_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="pospayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="pos_payment_amount_positive",
            ),
        ),
    ]
