# Generated by Django 5.2.17 on 2026-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0030_seed_pos_roles_and_tenders"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
