# Generated by Django 5.1.1 on 2026-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryledgerentry",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("SALE", "Sale"),
                    ("RETURN", "Return"),
                    ("TRANSFER_SHIPMENT", "Transfer shipment"),
                    ("TRANSFER_RECEIPT", "Transfer receipt"),
                    ("ADJUSTMENT_POSITIVE", "Positive adjustment"),
                    ("ADJUSTMENT_NEGATIVE", "Negative adjustment"),
                    ("OPENING", "Opening"),
                    ("COUNT", "Physical count"),
                    ("RECLASSIFICATION", "Reclassification"),
                    ("REPAIR", "Repair"),
                    ("QC", "QC"),
                    ("DAMAGE", "Damage"),
                    ("STATUS", "Status change"),
                    ("ASSEMBLY", "Assembly"),
                    ("DISASSEMBLY", "Disassembly"),
                    ("PRODUCTION", "Production"),
                    ("TRANSFER_LOSS", "Transfer short close"),
                    ("REVERSAL", "Reversal"),
                    ("CONSUMPTION", "Production consumption"),
                    ("OUTPUT", "Production output"),
                    ("SCRAP", "Production scrap"),
                    ("REVALUATION", "Revaluation"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="jewelleryunit",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("RESERVED", "Reserved"),
                    ("PICKED", "Picked"),
                    ("IN_TRANSIT", "In transit"),
                    ("QC", "In QC"),
                    ("DAMAGED", "Damaged"),
                    ("REPAIR", "In repair"),
                    ("BLOCKED", "Blocked"),
                    ("SOLD", "Sold"),
                    ("MISSING", "Missing"),
                    ("SCRAPPED", "Scrapped"),
                    ("RETURNED_TO_VENDOR", "Returned to vendor"),
                    ("NOT_IN_STOCK", "Not yet received"),
                    ("CONSUMED", "Consumed in production"),
                ],
                default="NOT_IN_STOCK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="replenishment_system",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transfer"),
                    ("PURCHASE", "Purchase"),
                    ("PRODUCTION", "Production"),
                    ("NONE", "None"),
                ],
                default="TRANSFER",
                max_length=20,
            ),
        ),
    ]
