# Generated by Django 5.1.1 on 2026-09-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventoryledgerentry_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryreservation",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("SALES_ORDER", "Sales order"),
                    ("QUOTATION", "Quotation"),
                    ("POS", "POS"),
                    ("CUSTOMER_ORDER", "Customer order"),
                    ("TRANSFER_ORDER", "Transfer order"),
                    ("PRODUCTION_ORDER", "Production order"),
                    ("REPAIR_ORDER", "Repair order"),
                    ("ECOMMERCE_ORDER", "E-commerce order"),
                    ("JOB_WORK_ORDER", "Job work order"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("STORE", "Store"),
                    ("WAREHOUSE", "Warehouse"),
                    ("DISTRIBUTION_CENTER", "Distribution centre"),
                    ("E_COMMERCE", "E-commerce"),
                    ("MANUFACTURING", "Manufacturing"),
                    ("REPAIR", "Repair"),
                    ("QC", "QC"),
                    ("RETURN", "Return"),
                    ("TRANSIT", "Transit"),
                    ("VIRTUAL", "Virtual"),
                    ("JOB_WORKER", "Job worker premises"),
                    ("OTHER", "Other"),
                ],
                default="STORE",
                max_length=30,
            ),
        ),
    ]
